<a href="https://colab.research.google.com/github/Dansouza-web/Caso-de-Estudo-De-Uma-Empresa-de-Biclietas-do-Curso-De-An-lise-de-Dados-do-Google/blob/main/Explora%C3%A7%C3%A3o.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
#primero vou puxar a base de dados
from google.colab import files
uploaded = files.upload()

Saving 202602-divvy-tripdata.csv to 202602-divvy-tripdata (1).csv

In [35]:
import pandas as pd
df = pd.read_csv('202602-divvy-tripdata.csv')
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,4194C9D5CAFDBE7C,electric_bike,2026-02-08 17:08:34.392,2026-02-08 17:13:57.661,NaN,NaN,NaN,NaN,41.95,-87.65,41.96,-87.65,member
1,790A93E87E5EE83C,electric_bike,2026-02-08 14:44:11.880,2026-02-08 14:48:14.329,NaN,NaN,NaN,NaN,41.89,-87.62,41.89,-87.62,member
2,21ABD91CD9FB7D13,electric_bike,2026-02-08 14:38:03.488,2026-02-08 14:41:19.976,NaN,NaN,NaN,NaN,41.94,-87.67,41.94,-87.66,member
3,8D97FE9075293A3B,electric_bike,2026-02-07 19:20:35.501,2026-02-07 19:20:58.619,NaN,NaN,NaN,NaN,41.90,-87.63,41.90,-87.63,member
4,03A65D965372A020,electric_bike,2026-02-07 20:47:02.949,2026-02-07 20:47:18.752,NaN,NaN,NaN,NaN,41.89,-87.62,41.89,-87.62,member

In [36]:
#Bom para o começo da minha exploração, eu vou utilizar um df.head() que me permite ver as 5 primeiras linhas da base de dados
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,4194C9D5CAFDBE7C,electric_bike,2026-02-08 17:08:34.392,2026-02-08 17:13:57.661,NaN,NaN,NaN,NaN,41.95,-87.65,41.96,-87.65,member
1,790A93E87E5EE83C,electric_bike,2026-02-08 14:44:11.880,2026-02-08 14:48:14.329,NaN,NaN,NaN,NaN,41.89,-87.62,41.89,-87.62,member
2,21ABD91CD9FB7D13,electric_bike,2026-02-08 14:38:03.488,2026-02-08 14:41:19.976,NaN,NaN,NaN,NaN,41.94,-87.67,41.94,-87.66,member
3,8D97FE9075293A3B,electric_bike,2026-02-07 19:20:35.501,2026-02-07 19:20:58.619,NaN,NaN,NaN,NaN,41.90,-87.63,41.90,-87.63,member
4,03A65D965372A020,electric_bike,2026-02-07 20:47:02.949,2026-02-07 20:47:18.752,NaN,NaN,NaN,NaN,41.89,-87.62,41.89,-87.62,member

In [37]:
#uso o df.info para ver a estrutura monatada do data set, e ver os tipos de dados
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201450 entries, 0 to 201449
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             201450 non-null  object
 1   rideable_type       201450 non-null  object
 2   started_at          201450 non-null  object
 3   ended_at            201450 non-null  object
 4   start_station_name  169381 non-null  object
 5   start_station_id    169381 non-null  object
 6   end_station_name    166589 non-null  object
 7   end_station_id      166589 non-null  object
 8   start_lat           201450 non-null  float64
 9   start_lng           201450 non-null  float64
 10  end_lat             201321 non-null  float64
 11  end_lng             201321 non-null  float64
 12  member_casual       201450 non-null  object
dtypes: float64(4), object(9)
memory usage: 20.0+ MB

In [39]:
#para ver o tamanho do data set
df.shape

(201450, 13)

In [ ]:
#para ver as colunas e os nomes das colunas e os tipos de dados das colunas
df.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='object')

In [ ]:
#uso o df.descibre para ver as metricas estatísticas mais comumns como média, mediana e moda
df.describe().round(2)

       start_lat  start_lng    end_lat    end_lng
count  201450.00  201450.00  201321.00  201321.00
mean       41.90     -87.65      41.90     -87.65
std         0.05       0.03       0.05       0.03
min        41.65     -87.82      41.65     -87.89
25%        41.88     -87.66      41.88     -87.66
50%        41.89     -87.64      41.89     -87.64
75%        41.93     -87.63      41.93     -87.63
max        42.07     -87.53      42.09     -87.53

In [ ]:
#verificando todos os valores nulos, e ve
df.isnull().sum()

ride_id                   0
rideable_type             0
started_at                0
ended_at                  0
start_station_name    32069
start_station_id      32069
end_station_name      34861
end_station_id        34861
start_lat                 0
start_lng                 0
end_lat                 129
end_lng                 129
member_casual             0
dtype: int64

In [31]:
#vendo as estações mais desembarcadas
df['start_station_name'].value_counts().head(10)

start_station_name
Canal St & Madison St             1577
Clinton St & Washington Blvd 2    1360
University Ave & 57th St          1357
State St & Chicago Ave            1310
Kingsbury St & Kinzie St 2        1275
Clinton St & Jackson Blvd         1232
Clinton St & Madison St           1123
Kingsbury St & Kinzie St 1        1114
Wells St & Elm St                 1029
Wells St & Concord Ln             1006
Name: count, dtype: int64

In [32]:

df['duracao'] = df['ended_at'] - df['started_at']
df = df[df['duracao'] > pd.Timedelta(minutes=1)]