<a href="https://colab.research.google.com/github/Dansouza-web/Caso-de-Estudo-De-Uma-Empresa-de-Biclietas-do-Curso-De-An-lise-de-Dados-do-Google/blob/main/Limpeza.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving 202602-divvy-tripdata.csv to 202602-divvy-tripdata.csv

In [2]:
import pandas as pd
df = pd.read_csv('202602-divvy-tripdata.csv')
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,4194C9D5CAFDBE7C,electric_bike,2026-02-08 17:08:34.392,2026-02-08 17:13:57.661,NaN,NaN,NaN,NaN,41.95,-87.65,41.96,-87.65,member
1,790A93E87E5EE83C,electric_bike,2026-02-08 14:44:11.880,2026-02-08 14:48:14.329,NaN,NaN,NaN,NaN,41.89,-87.62,41.89,-87.62,member
2,21ABD91CD9FB7D13,electric_bike,2026-02-08 14:38:03.488,2026-02-08 14:41:19.976,NaN,NaN,NaN,NaN,41.94,-87.67,41.94,-87.66,member
3,8D97FE9075293A3B,electric_bike,2026-02-07 19:20:35.501,2026-02-07 19:20:58.619,NaN,NaN,NaN,NaN,41.90,-87.63,41.90,-87.63,member
4,03A65D965372A020,electric_bike,2026-02-07 20:47:02.949,2026-02-07 20:47:18.752,NaN,NaN,NaN,NaN,41.89,-87.62,41.89,-87.62,member

In [3]:
#primeiro vou começar somando e verificando quando
df.isnull().sum()

ride_id                   0
rideable_type             0
started_at                0
ended_at                  0
start_station_name    32069
start_station_id      32069
end_station_name      34861
end_station_id        34861
start_lat                 0
start_lng                 0
end_lat                 129
end_lng                 129
member_casual             0
dtype: int64

In [5]:
#agoro resolvo remover as linhas com valores nulos pra ter uma eficiencia melhor pra analise
df = df.dropna()

In [7]:
df.isnull().sum()

ride_id               0
rideable_type         0
started_at            0
ended_at              0
start_station_name    0
start_station_id      0
end_station_name      0
end_station_id        0
start_lat             0
start_lng             0
end_lat               0
end_lng               0
member_casual         0
dtype: int64

In [10]:
#e sigo o mesmo passo com os dados duplicados
df.duplicated().sum()

np.int64(0)

In [11]:
df= df.drop_duplicates()

In [13]:
#mudando o tipo de dado de colunas que contem horas/data/dia ou datetime
df['started_at']=pd.to_datetime(df['started_at'])
df['ended_at']=pd.to_datetime(df['ended_at'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 147622 entries, 249 to 201449
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             147622 non-null  object
 1   rideable_type       147622 non-null  object
 2   started_at          147622 non-null  datetime64[ns]
 3   ended_at            147622 non-null  datetime64[ns]
 4   start_station_name  147622 non-null  object
 5   start_station_id    147622 non-null  object
 6   end_station_name    147622 non-null  object
 7   end_station_id      147622 non-null  object
 8   start_lat           147622 non-null  float64
 9   start_lng           147622 non-null  float64
 10  end_lat             147622 non-null  float64
 11  end_lng             147622 non-null  float64
 12  member_casual       147622 non-null  object
dtypes: datetime64[ns](2), float64(4), object(7)
memory usage: 15.8+ MB

In [30]:
#criando uma coluna para o tempo de viagem
df['duration_travel']= df['ended_at']-df['started_at']
df.head()
#e convertendo para horas pra ter uma melhor visualização na hora de análisar os dados
df['duration_travel_hours']= df['duration_travel'].dt.total_seconds() / 60
df.duration_travel_hours.round()

249         9.0
614        14.0
615        28.0
1688       10.0
1726       11.0
          ...
201445    194.0
201446     56.0
201447      4.0
201448      3.0
201449      4.0
Name: duration_travel_hours, Length: 147622, dtype: float64

In [31]:
#mudando os nomes das colunas para uma análise mais facil
df.columns =df.columns.str.lower()

In [33]:
#adicionando colunas úteis para a analíse
#dia da semana
df['day_of_week']=df['started_at'].dt.day_name()
#hora
df['hour']=df['started_at'].dt.hour